name: Vivazza
description: The Fashion Blog
meta-description: Vivazza is a fashion blog that features contemporary apparel and accessories.
url: http://www.vivazza.net
baseurl: /
domain: vivazza.net
commentlinks: true
google-analytics-tracking-id: UA-16909425-8

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      true
lsi:         false
markdown:    kramdown
permalink:   /notes/:title/
paginate:    1
gems: [jekyll-paginate]

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false